[db]
filename = "database.db"

[discord]
support_info = "Ping {} for any questions"
rust_version_info = "latest nightly from rustup"
hw_info = >- 
    Benchmarks are run in a controlled sandbox with limited resources.
methedology = >-
    You benchmark is first ran for 5 seconds to warm up the cores, and then benchmarked 
    for another 5. Please do not memoize any values in global state, a call to `run` 
    should always perform all of the work. Submissions may be manually reviewed.

[aoc]
inputs_dir = "/home/elf/aoc_inputs/"